### ISSUE TITLE
Zpětná vazba

### ISSUE THREAD

**Issue by ifischerova** [MijaHinn/PROJEKT-Sluzby#1]
Ahoj Míšo, 

děkuju za odevzdání, prima práce 👍 

Když se na řešení podívám přes DevTools, je vidět že obsah na několika místech "vytéká" z body a na mobilu nefunguje stránka úplně responzivně. 

Pomoci by mělo
- všechny `<section>` ještě zabalit do `divu`, ten pojmenovat třeba `kontejner` a udělat z něj sloupcový flexbox a nastavit mu padding 60px nahoře + dole a 20px po stranách:
```
    padding: 60px 20px;
    display: flex;
    justify-content: center;
    flex-direction: column;
    align-items: center;
```

- u samotných `<section>` vypnout všechny `marginy` a  nastavit sloupcový flexbox pro jejich obsah (sloupce pak u desktopu bude třeba změnit na řady) . `min-width` pak změnit na `max-width`, což by mělo zajistit, že se obsah bude zmenšovat/zvětšovat, ale nebude širší než 460px, jak je v designu. 
- u `.traveler` také smazat `margin` a `max-width` změnit na `width: 100%`. 
- pak bude asi potřeba si trochu pohrát s rozestupy u jednotlivých prvků v sekcích.

**Comment by MijaHinn** [comment]
Ahoj Ivko, tak snad vše opraveno. Chápu tedy správně, že je vždy lepší si tam ten obalový `kontejner` udělat?

**Comment by ifischerova** [comment]
Ahoj Míšo, vše v pohodě, vypadá to dobře 👍 💯 
Pokud jde o ten kontejner, nechci ti tvrdit, že to je vždy lepší, zkrátka záleží na daném layoutu. Ale za sebe musím říct, že v případě jako je tento a s tím, co umím, bych ho použila vždy, protože to dost usnadní práci (tím ale netvrdím, že to bez něj nejde udělat...:) ).  vím, že je to taková trochu "šalamounská" odpověď, ale zatím jsem nenarazila moc na to, že by byla jen jedna správná možnost řešení, taky nás trochu limituje to, co umíme a naše zkušenosti ;-)
